apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: myprojectuser
  POSTGRES_DB: myproject
  DB_HOST: db-service
  DB_PORT: '5432'

