apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db 
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 5432 #container port
      port: 5432 #pod port