apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
    
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/auriga/pv-backend" #this is the path of the node path means minikube(not local)
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: backend-pvc
    namespace: default