apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
  # labels: 
  #   volume-type: pv
    
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/auriga/pv"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: db-pvc
    namespace: default