apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  # selector:
  #   matchLabels:
  #     volume-type: pv