# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-ss
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgresql-container
          image: postgres:12
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
          ports:
          - containerPort: 5432
      #     volumeMounts:
      #       - name: db-volume
      #         mountPath: /var/lib/postgresql/data/
      # volumes:
      #   - name: db-volume
      #     persistentVolumeClaim:
      #       claimName: db-pvc
